apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
  labels:
    app: notes-backend
spec:
  selector:
    app: notes-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP